node {
    projectName = "examples.java";
    gitUrl = "https://github.com/krishnamanchikalapudi/${projectName}"

    approvers = "krishna";
   
    stageCheck="";
    stage ("Source Code") {
        stage ("> checkout") {
            try {
               git ( [ url: "$gitUrl", 
                        branch: "develop", 
                        credentialsId: 'GitHub.com'
                    ] )
               sh """ #!/bin/bash
                ls -lart
                cd SpringRestBoot
               """
               stageCheck += "<br/> Source Code > checkout: <font color='green'><b>OK</b></font>"
            } catch (ex) {
               stageCheck += "<br/> Source Code > checkout: <font color='red'><b>ERROR</b></font>"
            }
        } 

        stage ("> compile") {
            try {
                timeout (time: 15, unit: 'MINUTES') {
                    sh """ #!/bin/bash
                        gradle clean build -x test 
                    """
                    stageCheck += "<br/> Source Code > compile: <font color='green'><b>OK</b></font>"
                } catch (ex) {
                    stageCheck += "<br/> Source Code > compile: <font color='red'><b>ERROR</b></font>"
                }
            }
        }
   }
   
   print "$stageCheck"

}